networks:
  app-network:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './cloud_storage_server/cloud_storage/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './cloud_storage_server/cloud_storage/nginx/server.conf:/etc/nginx/conf.d/server.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    build:
      context: ./cloud_storage_server/cloud_storage
    networks:
      - app-network
  volumes:
    - ./var/www/uploads:/usr/src/app/users_files

  frontend:
    build:
      context: ./cloud_storage_client
    networks:
      - app-network